<?php

namespace TodoList\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaRepository extends EntityRepository
{
}
