<?php

namespace TodoList\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarefaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarefaRepository extends EntityRepository
{
  private function getQueryBuilder()
  {
      $em = $this->getEntityManager();

      $queryBuilder = $em->getRepository('TodoListCoreBundle:Tarefa')
      ->createQueryBuilder('p');

      return $queryBuilder;
   }

   public function findAllInOrder()
  {
      $qb = $this->getQueryBuilder()
      ->orderBy('p.criadoEm', 'desc');

      return $qb->getQuery()->getResult();
  }

}
